services:
  - type: web
    name: fta-app
    env: node
    buildCommand: ./build.sh
    startCommand: npm start
    autoDeploy: true
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
